# ~/.zprofile

# Only unique entries
typeset -U path

# PATH is already set in .profile which is sourced in zshenv
# path=("$HOME/.local/bin" /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/sbin /sbin "$path[@]")

typeset -U fpath

if [ -d "$HOMEBREW_PREFIX/share/zsh/site-functions" ]; then
	fpath=("$HOMEBREW_PREFIX/share/zsh/site-functions" $fpath)
fi

if [ -d "$ZSH_DATA_HOME/site-functions" ]; then
	fpath=("$ZSH_DATA_HOME/site-functions" $fpath)
fi
