# ~/.zprofile

#-- Path -----------------------------------------------------------------------

typeset -U path # only unique entries

path=("$HOME/.local/bin" /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/sbin /sbin "$path[@]")
