# ~/.zshenv

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export ZSH_CONFIG_HOME=$XDG_CONFIG_HOME/zsh
export ZSH_CACHE_HOME=$XDG_CACHE_HOME/zsh

export HOMEBREW_CASK_OPTS="--appdir=/Applications"
