# ~/.zshrc is sourced in interactive shells.

bindkey -e # Emacs keybindings

setopt AUTO_PUSHD         # Any directory changing command is treated as pushd
DIRSTACKSIZE=8
setopt NO_BEEP            # Never beep

source $ZSH_CONFIG_HOME/aliases.zsh
source $ZSH_CONFIG_HOME/completion.zsh
source $ZSH_CONFIG_HOME/history.zsh
source $ZSH_CONFIG_HOME/prompt.zsh
