# Denne filen utf√|res n√}r et loginshell (bash) avslutter.

# Utf|r f|rst den globale logoutfilen, IKKE kopier den filen, da er du
# n√¶rmest garantert at ting vil slutte√• virke om det blir √∏dvendig√
# gj√∏re endringer.

[ -f /local/lib/setupfiles/bash_logout ] && . /local/lib/setupfiles/bash_logout
