# -*- mode: shell-script; fill-column: 72; -*-
# ~/.bashrc

# source the system wide bashrc if it exists
if [ -e /etc/bash.bashrc ] ; then
  source /etc/bash.bashrc
fi

if [ -e /local/lib/setupfiles/bashrc ] ; then
		source /local/lib/setupfiles/bashrc
fi

# Aliases
if [ -e ${BASH_CONFIG_HOME}/aliases.bash ] ; then
	source ${BASH_CONFIG_HOME}/aliases.bash
fi

# Liquid Prompt
if [ -f /usr/local/share/liquidprompt ]; then
	[[ $- = *i* ]] && source /usr/local/share/liquidprompt;
elif [ -f ${XDG_DATA_HOME}/liquidprompt ]; then
	[[ $- = *i* ]] && source ${XDG_DATA_HOME}/liquidprompt;
fi

# Load direnv
which direnv &> /dev/null && eval "$(direnv hook bash)"
