# -*- mode: shell-script; fill-column: 72; -*-
# ~/.bash_profile: executed by bash for login shells.

if [ -e "${HOME}/.profile" ] ; then
	. ${HOME}/.profile
fi

# export EDITOR=vim
# export VISUAL=vim
# export PAGER=less

# export LC_CTYPE=en_US.UTF-8
# export LC_ALL=en_US.UTF-8

# History
#HISTFILE=${BASH_CACHE_HOME}/bash_history

# source the users bashrc if it exists
if [ -e "${HOME}/.bashrc" ]; then
  . "${HOME}/.bashrc"
fi

if [ -e ${HOME}/.nix-profile/etc/profile.d/nix.sh ]; then
   . ${HOME}/.nix-profile/etc/profile.d/nix.sh;
fi

export PYTHONUSERBASE="$HOME/.local"
