# -*- mode: shell-script; fill-column: 72; -*-
# ~/.bashrc

# source the system wide bashrc if it exists
if [ -e /etc/bash.bashrc ] ; then
	. /etc/bash.bashrc
fi

if [ -e /local/lib/setupfiles/bashrc ] ; then
	source /local/lib/setupfiles/bashrc
fi

# Aliases
if [ -e ${DOT_BASH}/aliases.bash ] ; then
	. ${DOT_BASH}/aliases.bash
fi

# Prompt
if [ -f $DOT_BASH/prompt.bash ]; then
	. $DOT_BASH/bash/prompt.bash
fi

# Load direnv
which direnv &> /dev/null && eval "$(direnv hook bash)"
